finddx/cdx

app/controllers/test_results_controller.rb
app/views/test_results/_filters.haml

Two url's will be used to get to test results so no need for this drop down .

#1570 fix, hide the test-order/tests drop down

---

app/models/device.rb
app/views/devices/_form.haml

Some weird hack required after much digging into chrome behaviour. I had to resort to setting two fake username and password fields right before the ones that were being populated and then hiding them. This seemed to trick chrome into treating these as the autocomplete fields. It seems setting `autocomplete="off"` attribute alone was not enough.

Fixes #1604

---

app/controllers/sites_controller.rb
app/views/sites/_form.html.haml
config/routes.rb

Hey @anthonyoleary  this is the only way I found to make the select update after the other select is updated.
What do you think?

Allow Sample ID Reset Policy and Manual Sample Entry options to be defined at Institution level

---

lib/tasks/ftp_monitor.rake

allow ftp monitor repeat time to be configurable: 
To use it repeat every 10 seconds: bundle exec rake ftp:start[10]

allow ftp monitor repeat time to be configurable

---

app/views/sites/_form.html.haml

Fixes error where sample id was populated but manual entry wasn't.

Populate manual entry based on parent site.

---

app/assets/javascripts/components/encounter_show.js.jsx
app/assets/javascripts/components/request_tests.js.jsx
app/controllers/encounters_controller.rb
app/controllers/patient_results_controller.rb
app/models/test_result_indexer.rb
app/views/culture_results/edit.haml
app/views/culture_results/new.haml
app/views/culture_results/show.haml
app/views/dst_lpa_results/edit.haml
app/views/dst_lpa_results/new.haml
app/views/dst_lpa_results/show.haml
app/views/microscopy_results/edit.haml
app/views/microscopy_results/new.haml
app/views/microscopy_results/show.haml
app/views/xpert_results/edit.haml
app/views/xpert_results/new.haml
app/views/xpert_results/show.haml
spec/controllers/encounters_controller_spec.rb
spec/features/encounter_spec.rb

#1860 A user should be taken to a different add results page based on the type of test.
A parameter is passed to the result page to indicate if the test order page is in 'edit' or 'cancel' mode on page back.
The logic is started to get complicated [and could be done in a cleaner way if had more time]

A user should be taken to a different add results page based on the type of test

---

app/assets/javascripts/components/request_tests.js.jsx

#1891 If a test status is set to reject then no result can be added or viewed,
#1859 If a test is set to pending or inprogress then a manual result can be added,If test is set to complete, then the lab tech can only view the result.
Fixed a test status <select> bug, there was a problem in the options used for reactjs whereby the status could not be correct set after changing.

#1891 test order rules to display/hide tests, fixed a status select bug.

---

app/models/encounter.rb
features/support/page_objects/new_encounter_page.rb
spec/controllers/encounters_controller_spec.rb
spec/features/encounter_spec.rb
spec/lib/reports/drtb_percentage_spec.rb
spec/lib/reports/drug_percentage_spec.rb
spec/models/device_message_processor_spec.rb
spec/models/encounter_spec.rb
spec/support/blueprints.rb

Now patient is mandatory for encounters.
Remember to check your database and make sure you have no encounters without a patient associated to it.

Enforce patient on encounters.

---

app/assets/javascripts/components/display_manifest.js.jsx.erb
app/controllers/device_models_controller.rb
app/views/device_models/_form.haml

#1873 Added validation when you delete a manifest,without uploading another an error message appears in you try and save the changes.
Due to the complex way of having a child model in the form and this child model can be replaced if you delete [hide the div] the manifest and upload [show the css] on the same page, it was cleaner to add a hidden form field to indicate if a manifest is deleted and do server side validation.
Initially tested a new delete action for the manifest but due to the device_model validations it was not best to just delete the manifest.
No json is used in the action call for this validation case, so just added a html response, if json is needed in the future we would need to decide how to add the error message to the API.

#1873 Added validation when you delete a manifest

---

lib/reports/devices_not_reporting.rb

#1955  When adding a new device to site the Device Not Reporting chart defaults to 366 days for that device

#1955 Device Not Reporting chart defaults to 366 days

---

app/policies/owner/institution.json.erb

Need to run: rake policy:update_roles, rake policy:calculate_computed when deployed.

fix for test orders header not displayed

---

config/secrets.yml

If you wanted to debug in development with say data from edge then you
can now specify the same secret in an environment variable. Use with
caution, with great power comes great responsibilty!!

Adds ability to supply a secret key in development

---

docker-compose.prod.yml

This will update the docker-compose-prod to use the finddx/cdx image instead of the instead/cdx image

Update the docker-compose-prod to use finddx/cdx

---

config/database.yml
db/seeds/manifests/genexpert_manifest.json

https://find.plan.io/issues/2450
I thought I had submitted this already.
Mapping 'event.patient_ID' and 'event.notes', to custom fields on the test order (as xpert_patient_number) and the sample (as xpert_number). Field names can change easily if requested.

2450-new-manifest-mapping

---

cdx_core/app/mailers/invitation_mailer.rb
cdx_core/app/middleware/persistence/users.rb

For some reason, sending email asyncrounsly loses the activation token
in the invitation email. Not sure this is the perfect fix, but should
suffice for now.

Fixes missing token in invitation email

---

Gemfile
Gemfile.lock

Doorkeeper failed to implement OAuth 2.0 Token Revocation (RFC 7009) in
the following ways:
-(1) Public clients making valid, unauthenticated calls to revoke a token
would not have their token revoked
-(2) Requests were not properly authenticating the client credentials but
were, instead, looking at the access token in a second location
-(3) Because of 2, the requests were also not authorizing confidential
clients' ability to revoke a given token. It should only revoke tokens
that belong to it.

Bumping doorkeeper version..

---

db/seeds/manifests/genexpert_manifest.json

Device messages erroneously report an error if MTB is not detected.

update seed genexpert manifest

---

Gemfile
Gemfile.lock
cdx_core/Gemfile
cdx_core/Gemfile.lock
cdx_core/app/mailers/notification_mailer.rb
cdx_core/app/middleware/notifications/gateway/email.rb
cdx_core/app/middleware/notifications/gateway/sms.rb
cdx_core/app/models/concerns/notification_observer.rb
cdx_core/app/models/notification.rb
cdx_core/app/models/notification/notice_group.rb
cdx_core/app/views/notification_mailer/aggregated.text.erb
cdx_core/lib/tasks/alerts.rake
cdx_core/spec/dummy/db/schema.rb
spec/mailers/previews/notification_mailer_preview.rb

To clear up the serialisation change the following needs to be run after deployment;
`rake convert_notice_groups`

add counts to aggregation messages & notification conditions validation

---

cdx_core/app/models/assay_result.rb
cdx_core/app/models/notification/condition.rb
cdx_core/spec/jobs/check_notification_job_spec.rb
cdx_core/spec/middleware/notifications/assay_result_lookup_spec.rb

Avoid firing off thousands of jobs when devices input historical data.

remove observer from AssayResult

---

cdx_core/app/views/encounters/show.html.haml
cdx_vietnam/Gemfile
cdx_vietnam/Gemfile.lock
cdx_vietnam/app/models/patient_decorator.rb
cdx_vietnam/config/locales/views/cdx_vietnam/patients.en.yml
cdx_vietnam/spec/models/patient_spec.rb

- Remove Create Alert from this Test Order button.
- Added `allow_blank` to CMND validation in `cdx_vietnam`

allow cmnd to be blank in vn / remove encounter alert link

---

cdx_core/app/models/device.rb
cdx_core/spec/controllers/devices_controller_spec.rb
cdx_core/spec/dummy/db/schema.rb
cdx_vietnam/app/middleware/test_orders/presenter_decorator.rb
db/seeds/manifests/genexpert_manifest.json

- Enforce `#time_zone` validation on Device / update tests
- Update Genexpert manifest example with timezone parsing and version
- Update test schema
- Fix spelling

Enforce timezone on device

---

cdx_vietnam/spec/middleware/importer/single_message_processor_spec.rb

Modified sample id linking test to include a character so that we can test matching with lowercase and uppercase values.

test for sample_id in lowercase

---

cdx_vietnam/app/middleware/middleware/integration/etb_scraper.rb

CMND (national id number) is no longer required for a patient to be copied to ETB Manager

CMND is no longer required

---

cdx_core/app/middleware/xpert_results/finder.rb
cdx_core/app/models/sample_identifier.rb
cdx_vietnam/app/middleware/xpert_results/vietnam_importer.rb
cdx_vietnam/app/views/addresses/_country_select_form.haml
cdx_vietnam/app/views/addresses/_region_form.html.haml
cdx_vietnam/spec/middleware/importer/single_message_processor_spec.rb
cdx_vietnam/spec/middleware/xpert_results/vietnam_importer_spec.rb
cdx_vietnam/spec/support/blueprints.rb

- If there is a sample_id on an encounter, but no valid sample_identifier to link to. Don't raise an error and fail the device message processing. Create an orphan.
- Don't link device_messages that are 'error', 'no_result', or 'invalid'.
- Don't default region/country on the patient form.

linking / patient form fixes
