finddx/cdx

- app/assets/javascripts/components/sites.js.jsx
- app/assets/stylesheets/_charts.scss
- app/controllers/api/institutions_controller.rb
- app/controllers/api/sites_controller.rb
- app/controllers/application_controller.rb
- app/controllers/institutions_controller.rb
- app/controllers/sites_controller.rb
- app/views/dashboards/index.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/layouts/application.html.haml
- app/views/shared/_header_nav.haml
- app/views/test_results/index.haml
- config/initializers/devise.rb
> Bf dashboard changes

- Gemfile.lock
- lib/tasks/load_manifests.rake
When single tenant load a single default instituion and not
manufacturers
> Update manifest task for single tenant

- app/controllers/patients_controller.rb
- app/controllers/sites_controller.rb
- app/models/concerns/with_location.rb
- app/models/patient.rb
- app/models/patient_form.rb
- app/views/patients/_filters.haml
- app/views/patients/_form.html.haml
- app/views/patients/index.html.haml
- app/views/shared/_address.html.haml
- app/views/sites/_filters.haml
- app/views/sites/_form.html.haml
- app/views/sites/_show.html.haml
- app/views/sites/index.html.haml
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- db/migrate/20160602211123_add_address_info_to_patients.rb
- db/schema.rb
- spec/controllers/api/messages_controller_locations_spec.rb
- spec/controllers/api/tests_controller_locations_spec.rb
- spec/controllers/patients_controller_spec.rb
- spec/controllers/sites_controller_spec.rb
- spec/controllers/test_results_controller_spec.rb
- spec/models/device_message_processor_spec.rb
- spec/models/manifest_operations_spec.rb
- spec/models/test_result_indexer_spec.rb
- spec/support/blueprints.rb
Add address fields to site and patent. Also remove the access to the location server.
> Add address fields to site and patent.

- app/controllers/devices_controller.rb
- app/controllers/institutions_controller.rb
- app/models/device.rb
- app/models/ftp_monitor.rb
- app/models/institution.rb
- app/views/devices/_form.haml
- app/views/institutions/_form.haml
- db/migrate/20160613092735_add_ftp_credentials_to_institutions.rb
- db/schema.rb
- spec/controllers/institutions_controller_spec.rb
- spec/models/device_spec.rb
- spec/models/ftp_monitor_spec.rb
#1520 
Ftp credentials now saved on institution instead of per device.
FtpMonitor updated to group ftp servers based on institutions instead of devices.
> 1520 ftp credentials on institution

- app/controllers/comments_controller.rb
- app/models/comment.rb
- app/models/patient.rb
- app/models/user.rb
- app/views/comments/_form.haml
- app/views/comments/new.haml
- app/views/patients/show.html.haml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20160614093412_add_comments_to_patients.rb
- db/schema.rb
- lib/extras/dates/format.rb
- spec/controllers/comments_controller_spec.rb
- spec/models/comment_spec.rb
- spec/spec_helper.rb
This solves stories: #1837 #1838 #1839 #1840
> Comments for patients

- app/controllers/audit_updates_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/patient_logs_controller.rb
- app/controllers/patients_controller.rb
- app/models/audit_update.rb
- app/models/comment.rb
- app/models/concerns/auditable.rb
- app/models/patient_form.rb
- app/views/comments/_form.haml
- app/views/comments/new.haml
- app/views/comments/show.haml
- app/views/patient_logs/show.haml
- lib/audit/auditor.rb
- spec/controllers/comments_controller_spec.rb
- spec/controllers/patients_controller_spec.rb
- spec/models/audit_update_spec.rb
- spec/models/patient_form_spec.rb
Fixed a problem where patient changes where not audited correctly because patient form uses it's own method to assign values to fields
> Changes audited for patients

- app/assets/stylesheets/_newdash.scss
- app/views/devices/_filters.haml
- app/views/devices/_form.haml
- app/views/devices/index.haml
- app/views/devices/new.haml
- app/views/patients/_filters.haml
- app/views/patients/edit.html.haml
- app/views/patients/index.html.haml
- app/views/patients/new.html.haml
- app/views/test_results/index.haml
Over site styling for main sections
> New site styles v3

- app/views/incidents/_filters.html.haml
- config/locales/views/settings.en.yml
> 1488 Settings Incidents Filter bar to show all filters in new style

- app/assets/javascripts/components/encounter_show.js.jsx
- app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- app/assets/javascripts/components/request_tests.js.jsx
- app/controllers/encounters_controller.rb
- db/migrate/20160712141015_add_testing_for_to_encounters.rb
- db/schema.rb
- features/support/page_objects/show_encounter_page.rb
- lib/presenters/test_orders.rb
- spec/features/encounter_spec.rb
- spec/presenters/test_orders_spec.rb
#1886 fixed, #1853, #1900, #1854 fixed
> added, testing for, field to encounter

- app/controllers/patients_controller.rb
- app/views/shared/_display_boolean_value.haml
- spec/audit/auditor_spec.rb
make check box reflect field value.
> 1914 result page errors

- app/controllers/xpert_results_controller.rb
- app/models/xpert_result.rb
- app/views/xpert_results/_form.haml
- app/views/xpert_results/show.haml
- config/locales/models/xpert_result.en.yml
- config/locales/select.en.yml
- db/migrate/20160715133242_add_trace_to_results.rb
- db/schema.rb
https://find.plan.io/issues/1919
> #1919 - Add trace for Xpert form.

- app/assets/javascripts/components/patients/patients_index_table.js.jsx
- app/assets/stylesheets/_tables.scss
- app/views/patients/_patient_summary.haml
- lib/presenters/patients.rb
- spec/presenters/patients_spec.rb
https://find.plan.io/issues/1927
> #1927 patient listing details

- app/assets/javascripts/components/test_orders/test_orders_list.js.jsx
- config/locales/models/encounters.en.yml
https://find.plan.io/issues/1925
> #1925 Change header names in test list.

- app/assets/javascripts/components/encounter_form.js.jsx
- app/assets/javascripts/components/encounter_new.js.jsx
- app/assets/javascripts/components/encounter_show.js.jsx
- app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- app/assets/javascripts/components/shared/display_field_with_label.js.jsx
- app/assets/javascripts/components/site_select.js.jsx
- app/controllers/encounters_controller.rb
- app/models/encounter.rb
- app/views/encounters/new.html.haml
- config/locales/views/encounters.en.yml
- db/migrate/20160717142201_add_culture_format_to_encounters.rb
- db/schema.rb
- spec/controllers/encounters_controller_spec.rb
- spec/models/encounter_spec.rb
** Please merge first 1928 as this PR depends on it **
https://find.plan.io/issues/1921
> #1921 culture test format

- app/assets/javascripts/components/encounter_form.js.jsx
- app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- app/controllers/culture_results_controller.rb
- app/controllers/encounters_controller.rb
https://find.plan.io/issues/1928
> #1928 new test order

- app/assets/javascripts/components/patient_card.js.jsx.erb
(Partially incomplete - needs styles from Shaun)
> 1855 user to see all patient info

- app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- app/views/test_results/index.haml
- config/locales/views/test_results.en.yml
> 1920 correct option for tb order

- app/assets/javascripts/components/encounter_show.js.jsx
- app/assets/javascripts/components/encounters/lab_samples_list.js.jsx
- app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- app/assets/javascripts/components/sample.js.jsx
- app/controllers/sample_identifiers_controller.rb
- app/views/encounters/show.html.haml
- config/locales/views/encounters.en.yml
- config/routes.rb
- spec/controllers/api/filtrs_controller_spec.rb
- spec/controllers/sample_identifiers_controller_spec.rb
This PR changes the way laboratory ids are added. Now it's in the test order show page.
> 1947 test order card amends

- app/assets/javascripts/components/policy_item_detail.js.jsx
If you edit a role ,such as remove a policy ,add it back in and select all actions [or any action], then there was a bug whereby no policy actions were added.
> #1952 modify role policy, the policy changes did not change.

- app/controllers/institutions_controller.rb
> Ensured Nav appears on edit institution scree #1893

- lib/reports/site.rb
This PR fixes a problem with edge and encounters with site = nil
> #1907 Check that site is present.

- app/assets/javascripts/components/test_results_list.js.jsx
- app/models/test_result.rb
- app/models/test_result_query.rb
> #1995 add device name and serial number

- app/assets/javascripts/components/test_results_list.js.jsx
- app/models/test_result.rb
- app/models/test_result_query.rb
> #1997 align results header

- app/assets/javascripts/components/encounter_show.js.jsx
- app/assets/javascripts/components/encounters/lab_samples_list.js.jsx
- app/assets/javascripts/components/request_tests.js.jsx
- app/controllers/dst_lpa_results_controller.rb
- app/controllers/encounters_controller.rb
- app/models/requested_test.rb
- app/views/encounters/show.html.haml
- config/locales/views/dst_lpa_results.en.yml
- spec/controllers/dst_lpa_results_controller_spec.rb
- spec/controllers/encounters_controller_spec.rb
- spec/models/requested_test_spec.rb
> #1998 cannot add dst before culture

- app/models/requested_test.rb
- spec/controllers/requested_tests_controller.rb
#1980 remove status 'Deleted' from tests on the edit test order page.
> #1980 remove status 'Deleted' from tests

- app/models/episode.rb
- app/views/episodes/_form.haml
for the droplist and radio, from the single hash (2003)
> Split Diagnoses into two separate references

- app/helpers/application_helper.rb
- app/models/concerns/resource.rb
- app/models/page_header.rb
- app/models/policy.rb
- app/policies/roles/institution/institution.json.erb
- app/policies/roles/institution/manufacturer.json.erb
- app/views/shared/_header_nav.haml
- db/migrate/20160722114857_create_page_headers.rb
- db/migrate/20160726103921_add_site_prefix_to_page_headers.rb
- db/schema.rb
- lib/tasks/policy.rake
- spec/models/computed_policy_spec.rb
- spec/models/policy_spec.rb
- spec/support/blueprints.rb
- spec/support/feature_spec_helpers.rb
#1910,#1911 added new page header policy to allow the control of displaying page headers.
> #1910,#1911 added new page header policy to allow displaying page headers

- app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- app/controllers/encounters_controller.rb
- app/models/entity_indexable_fields.rb
- spec/models/encounter_indexer_spec.rb
> Fix validation error adding encounters.

- lib/reports/site.rb
This is more a hack than an actual fix.  There should be no data with an empty site.
> Check that site is present.

- app/assets/javascripts/components/request_tests.js.jsx
#1981 A Technician shouldn't be able to set Test Status to Complete if no result has been added. The complete status will not be displayed if there is no result added.
> #1981 A Technician shouldn't be able to set Test Status to Complete if no result has been added

- app/helpers/application_helper.rb
- app/models/concerns/resource.rb
- app/models/policy.rb
- app/models/settings_page.rb
- app/policies/owner/institution.json.erb
- app/policies/roles/institution/institution.json.erb
- app/policies/roles/institution/manufacturer.json.erb
- app/views/home/settings.html.haml
- db/migrate/20160727135031_create_settings_pages.rb
- db/schema.rb
- lib/tasks/policy.rake
- spec/models/computed_policy_spec.rb
- spec/models/policy_spec.rb
- spec/support/blueprints.rb
> added settings page policy

- app/assets/javascripts/components/patients/show/history/patient_test_order.js.jsx
- app/assets/javascripts/components/patients/show/history/patient_test_orders.js.jsx
- app/assets/javascripts/components/patients/show/patient_test_order.js.jsx
- app/assets/javascripts/components/patients/show/patient_test_orders.js.jsx
- app/assets/stylesheets/_testflow.scss
- app/models/episode.rb
- config/environments/development.rb
- db/schema.rb
- lib/presenters/patient_test_orders.rb
- lib/presenters/test_orders.rb
- spec/models/episode_spec.rb
- spec/presenters/patient_test_orders_spec.rb
- spec/presenters/test_orders_spec.rb
Please ignore the files in the show/history folder.
> 2007 2012 test order list updates

- app/assets/javascripts/components/navigation_context_picker.js.jsx
- app/assets/javascripts/components/sites.js.jsx
Fixed bug where navigation sub site checkbox change was not remembered on a page refresh.
> Navigation sub site checkbox change was not remembered.

- app/assets/javascripts/components/request_tests.js.jsx
- app/controllers/dst_lpa_results_controller.rb
> Check new types of dst tests.

- lib/presenters/episodes.rb
- spec/presenters/episodes_spec.rb
missing hiv-status,outcome,drug-resistance fields in patient summary page.
> missing patient summary page fields

- app/assets/javascripts/components/patients/show/episodes/show_patient_episode.js.jsx
- app/views/episodes/_form.haml
- lib/presenters/episodes.rb
- spec/presenters/episodes_spec.rb
anatomical_site_diagnosis from episodes was not saved or displayed
> anatomical_site_diagnosis from episodes was not saved or displayed

- app/controllers/episodes_controller.rb
for an episode redirect to the edit page if there is an update error
> for an episode redirect to the edit page if there is an update error

- app/controllers/patients_controller.rb
- app/views/patients/_filters.haml
- config/locales/views/patients.en.yml
> Updated version of Remember Patient Params for Filters

- app/assets/javascripts/components/encounters/requested_tests.js.jsx
- app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- app/controllers/encounters_controller.rb
- spec/controllers/encounters_controller_spec.rb
> requested test order checkboxes

- app/assets/javascripts/components/patients/patients_index_table.js.jsx
- app/assets/javascripts/components/shared/highlighter.js.jsx
- app/assets/stylesheets/_custom.scss
- app/controllers/patients_controller.rb
- app/middleware/patients/finder.rb
- app/views/patients/_filters.haml
- app/views/patients/edit.html.haml
- app/views/patients/index.html.haml
- app/views/patients/new.html.haml
- config/locales/views/patients.en.yml
- lib/presenters/patients.rb
- lib/reports/site.rb
- spec/controllers/patients_controller_spec.rb
- spec/middleware/patients/finder_spec.rb
- spec/presenters/patients_spec.rb
Remove last encounter and add search by address and date of birth
>  remove last encounter

- app/assets/javascripts/components/patients/show/patient_test_order.js.jsx
- app/assets/javascripts/components/patients/show/patient_test_orders.js.jsx
This responsibility lies with individual tests completes ticket #255
> Removes concept of turnaround from TestOrder

- app/assets/javascripts/components/alert_child_components.js.jsx
> Fixes 2117 cannot create alert group

- app/middleware/test_orders/finder.rb
- app/models/encounter.rb
- app/views/test_orders/index.haml
- config/locales/select.en.yml
- config/locales/views/test_orders.en.yml
- spec/controllers/test_orders_controller_spec.rb
- spec/middleware/test_orders/finder_spec.rb
https://find.plan.io/issues/2061
> Show pending and in progress test orders by default.

- app/assets/javascripts/components/test_results/culture_results.js.jsx
- app/controllers/test_results_controller.rb
- app/middleware/test_results/finder.rb
- app/views/culture_results/_form.haml
- lib/presenters/culture_results.rb
- lib/presenters/xpert_results.rb
- spec/middleware/test_results/finder_spec.rb
- spec/presenters/culture_results_spec.rb
- spec/presenters/xpert_results_spec.rb
https://find.plan.io/issues/2131
> Fix 404 error when clicking on xpert, culture results.

- .gitignore
- Gemfile.lock
- cdx_core/README.rdoc
- cdx_core/app/views/devices/_secret_key.haml
- cdx_core/app/views/devices/setup.haml
- cdx_core/config/locales/views/patient_test_results.en.yml
- cdx_core/lib/presenters/patient_test_results.rb
- cdx_core/spec/controllers/patient_test_results_controller_spec.rb
- cdx_core/spec/presenters/patient_test_results_spec.rb
- cdx_core/spec/presenters/xpert_results_spec.rb
- cdx_vietnam/cdx_vietnam.gemspec
https://find.plan.io/issues/2142
> Patient history results

- cdx_core/app/middleware/test_results/finder.rb
- cdx_core/app/views/test_results/_culture_results.haml
- cdx_core/app/views/test_results/_dst_lpa_results.haml
- cdx_core/app/views/test_results/_filters.haml
- cdx_core/app/views/test_results/_microscopy_results.haml
- cdx_core/app/views/test_results/_xpert_results.haml
- cdx_core/lib/finder/manual_results.rb
- cdx_core/spec/controllers/test_results_controller_spec.rb
https://find.plan.io/issues/2153
> Search test results by serial number

- .travis.yml
- Fudgefile
- Gemfile
- Gemfile.lock
Travis should now build cdx_core subdirectory
> Fixes travis

- Fudgefile
- cdx_core/app/controllers/institutions_controller.rb
- cdx_core/app/controllers/sites_controller.rb
- cdx_core/app/views/test_orders/index.haml
- cdx_core/config/locales/views/institutions.en.yml
- cdx_core/config/locales/views/sites.en.yml
- cdx_core/config/locales/views/test_orders.en.yml
- cdx_core/spec/controllers/sites_controller_spec.rb
- cdx_core/spec/controllers/xpert_results_controller_spec.rb
- cdx_vietnam/Gemfile.lock
- circle.yml
https://find.plan.io/issues/2067
> Xpert result validation

- Gemfile.lock
- cdx_core/app/assets/javascripts/components/encounter_show.js.jsx
- cdx_core/app/assets/javascripts/stores/EncounterStore.js.jsx
- cdx_core/app/controllers/encounters_controller.rb
- cdx_core/app/views/encounters/show.html.haml
- cdx_core/spec/controllers/encounters_controller_spec.rb
https://find.plan.io/issues/2059
> Improve checking.

- cdx_api_core/spec/support/blueprints.rb
- cdx_core/app/assets/javascripts/components/devices/devices_index_table.js.jsx
- cdx_core/app/controllers/device_models_controller.rb
- cdx_core/app/controllers/devices_controller.rb
- cdx_core/app/models/device_message_processor.rb
- cdx_core/app/models/encounter.rb
- cdx_core/app/models/institution.rb
- cdx_core/app/models/sample_identifier.rb
- cdx_core/app/views/device_models/_publish.haml
- cdx_core/app/views/device_models/show.haml
- cdx_core/app/views/devices/_filters.haml
- cdx_core/app/views/devices/index.csv.csvbuilder
- cdx_core/app/views/encounters/show.html.haml
- cdx_core/app/views/institutions/_form.haml
- cdx_core/config/locales/views/device_models.en.yml
- cdx_core/lib/presenters/devices.rb
- cdx_core/spec/controllers/device_models_controller_spec.rb
- cdx_core/spec/controllers/devices_controller_spec.rb
- cdx_core/spec/features/device_model_spec.rb
- cdx_core/spec/models/device_message_processor_spec.rb
- cdx_core/spec/models/policy_spec.rb
- cdx_core/spec/models/sample_identifier_spec.rb
- cdx_core/spec/presenters/devices_spec.rb
- cdx_core/spec/support/blueprints.rb
https://find.plan.io/issues/1548
> Remove manufacturers from code.

- cdx_core/app/controllers/sites_controller.rb
- cdx_core/config/locales/views/sites.en.yml
- cdx_core/lib/csv_generator/sites.rb
- cdx_core/spec/controllers/sites_controller_spec.rb
- cdx_core/spec/lib/csv_generator/sites_spec.rb
https://find.plan.io/issues/2191
> Update sites information and parent.

- Gemfile.lock
- cdx_core/app/assets/javascripts/components/encounter_show.js.jsx
- cdx_core/app/assets/javascripts/components/modal.js.jsx
- cdx_core/app/views/encounters/new.html.haml
- cdx_core/spec/presenters/patients_spec.rb
https://find.plan.io/issues/1934
> Add changes back 1934

- cdx_core/app/assets/javascripts/components/roles/policy_item.js.jsx
- cdx_core/config/locales/controllers/api.en.yml
- cdx_core/config/locales/controllers/controllers.en.yml
- cdx_core/config/locales/models/concerns.en.yml
- cdx_core/config/locales/views/encounters.en.yml
- cdx_core/config/locales/views/home.en.yml
- cdx_core/config/locales/views/js_screen_views.en.yml
- cdx_core/config/locales/views/test_results.en.yml
- cdx_core/spec/controllers/encounters_controller_spec.rb
- cdx_vietnam/config/locales/controllers/api.vi.yml
https://find.plan.io/issues/2187
> Rename encounter to test order.

- cdx_core/app/views/institutions/_list.haml
- cdx_core/app/views/institutions/index.haml
- cdx_vietnam/app/controllers/institutions_controller_decorator.rb
- cdx_vietnam/app/views/institutions/index.haml
- cdx_vietnam/config/locales/views/institutions.en.yml
https://find.plan.io/issues/2208
> Add institutions in cdx_vietnam is not allowed.

- cdx_core/app/assets/javascripts/components/patients/show/episodes/show_patient_episode.js.jsx
- cdx_core/app/models/episode.rb
- cdx_core/config/locales/select.en.yml
> Update fields in Episode Display form.

- cdx_core/app/assets/javascripts/components/patients/form/patient_input_name.js.jsx
- cdx_core/app/assets/javascripts/components/shared/tooltip_label.jsx
- cdx_vietnam/app/assets/javascripts/application.js
- cdx_vietnam/app/assets/javascripts/components/patients/social_security_code.js.jsx
- cdx_vietnam/app/models/patient.rb
- cdx_vietnam/app/views/patients/_form.html.haml
- cdx_vietnam/config/locales/views/cdx_vietnam/patients.en.yml
- cdx_vietnam/config/locales/views/cdx_vietnam/patients.vi.yml
- cdx_vietnam/config/locales/views/cdx_vietnam/patients.vi.yml~
- cdx_vietnam/config/locales/views/js_components.vi.yml
- cdx_vietnam/lib/cdx_vietnam/engine.rb
- cdx_vietnam/spec/models/patient_spec.rb
https://find.plan.io/issues/2259
> Include js files in cdx_vietnam.

- Gemfile
- cdx_core/app/assets/stylesheets/_newlayout.scss
- cdx_core/app/views/addresses/_form.haml
- cdx_core/app/views/devise/registrations/edit.html.haml
- cdx_core/app/views/patients/_form.html.haml
- cdx_core/config/locales/views/addresses.en.yml
- cdx_vietnam/app/views/patients/_form.html.haml
This was rebased before pushing, yet it still has other files in there.
Gemfile and registrations/edit are from commits elsewhere.
> Patient pages address label changes

- cdx_core/app/assets/javascripts/components/approvals/approval_row.jsx
- cdx_core/app/assets/javascripts/components/approvals/approvals_table.js.jsx
- cdx_core/app/controllers/approvals_controller.rb
- cdx_core/app/middleware/test_orders/finder.rb
As discussed, scope by site. Also, fix table column sort id.
> Fix approvals#index site context

- cdx_core/app/assets/javascripts/components/patients/show/history/patient_test_orders.js.jsx
- cdx_core/config/locales/select.en.yml
- cdx_vietnam/app/assets/javascripts/components/patients/show/history/patient_test_orders.js.jsx
https://find.plan.io/issues/2343
> Remove empty column.

- cdx_core/config/locales/views/js_components.en.yml
https://find.plan.io/issues/2341
> Add missing translation

- cdx_core/app/assets/javascripts/components/test_batch/show_completed_test_result.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/show_rejected_with_comment.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_row.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_result_status.js.jsx
- cdx_core/app/middleware/patient_results/presenter.rb
- cdx_core/app/views/culture_results/_form.haml
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/spec/middleware/patient_results/presenter_spec.rb
- cdx_vietnam/app/assets/javascripts/components/encounter_show.js.jsx
https://find.plan.io/issues/2347
> Add view results link to completed and rejected.

- cdx_core/app/middleware/test_orders/finder.rb
- cdx_core/app/views/test_orders/index.haml
- cdx_core/spec/middleware/test_orders/finder_spec.rb
https://find.plan.io/issues/2333
> Add filter by batch id.

- cdx_core/app/assets/javascripts/components/test_batch/add_samples_action.js.jsx
https://find.plan.io/issues/2349
> Fix cancel link problem.

- cdx_core/app/assets/javascripts/components/test_batch/show_approve_test_result.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/show_completed_test_result.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/show_rejected_with_comment.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_row.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_result_status.js.jsx
- cdx_core/app/middleware/patient_results/presenter.rb
- cdx_core/app/views/culture_results/_form.haml
- cdx_core/app/views/culture_results/show.haml
- cdx_core/app/views/dst_lpa_results/show.haml
- cdx_core/app/views/microscopy_results/show.haml
- cdx_core/app/views/xpert_results/show.haml
- cdx_core/config/locales/models/culture_result.en.yml
- cdx_core/config/locales/models/dst_lpa_result.en.yml
- cdx_core/config/locales/models/microscopy_result.en.yml
- cdx_core/config/locales/models/xpert_result.en.yml
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/spec/middleware/patient_results/presenter_spec.rb
- cdx_vietnam/app/assets/javascripts/components/encounter_show.js.jsx
https://find.plan.io/issues/2348
> show test results comment

- cdx_core/app/assets/javascripts/components/patient_card.js.jsx.erb
https://find.plan.io/issues/2334
> Remove gender from patient info.

- cdx_core/config/locales/views/js_screen_views.en.yml
https://find.plan.io/issues/2335
> Rename address in patient card.

- cdx_core/app/assets/javascripts/components/approvals/approval_row.jsx
https://find.plan.io/issues/2338
> Remove order id from approvals table.

- cdx_core/app/assets/javascripts/components/approvals/approvals_table.js.jsx
- cdx_core/config/locales/views/js_components.en.yml
https://find.plan.io/issues/2339
> Rename sample id into order id.

- cdx_core/app/assets/javascripts/components/test_batch/test_batch_row.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_table.js.jsx
- cdx_core/config/locales/views/js_components.en.yml
https://find.plan.io/issues/2344
> Add test status to test results.

- cdx_core/app/middleware/test_orders/finder.rb
- cdx_core/app/models/encounter.rb
- cdx_core/config/locales/select.en.yml
- cdx_core/spec/controllers/test_orders_controller_spec.rb
- cdx_core/spec/models/encounter_spec.rb
https://find.plan.io/issues/2337
> Update status filter.

- cdx_core/app/assets/javascripts/components/patients/show/history/patient_test_order.js.jsx
- cdx_core/app/middleware/concerns/test_orders/presenter.rb
- cdx_core/app/models/xpert_result.rb
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/spec/middleware/test_orders/presenter_spec.rb
https://find.plan.io/issues/2342
> Show sample ids from serial number of test results.

- cdx_core/app/assets/javascripts/components/test_batch/test_result_actions.js.jsx
- cdx_core/config/locales/views/js_components.en.yml
https://find.plan.io/issues/2382
> Update sample received button text.

- cdx_core/app/assets/javascripts/components/test_batch/show_approve_test_result.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/show_completed_test_result.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_row.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_table.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_result_status.js.jsx
- cdx_core/app/middleware/test_orders/status.rb
- cdx_core/app/models/culture_result.rb
- cdx_core/app/models/dst_lpa_result.rb
- cdx_core/app/models/microscopy_result.rb
- cdx_core/app/models/patient_result.rb
- cdx_core/app/models/xpert_result.rb
- cdx_core/config/locales/select.en.yml
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/spec/middleware/patient_results/persistence_spec.rb
- cdx_core/spec/middleware/test_orders/presenter_spec.rb
- cdx_core/spec/middleware/test_orders/status_spec.rb
- cdx_core/spec/models/culture_result_spec.rb
- cdx_core/spec/models/dst_lpa_result_spec.rb
- cdx_core/spec/models/microscopy_result_spec.rb
- cdx_core/spec/models/xpert_result_spec.rb
- cdx_vietnam/app/assets/javascripts/components/encounter_show.js.jsx
- cdx_vietnam/spec/middleware/test_orders/presenter_spec.rb
https://find.plan.io/issues/2384
> Rename samples received status

- cdx_core/app/views/episodes/_form.haml
- cdx_core/config/locales/views/episodes.en.yml
> client side validation of field choice

- cdx_core/app/assets/javascripts/components/test_batch/show_rejected_with_comment.js.jsx
- cdx_core/app/controllers/culture_results_controller.rb
- cdx_core/app/controllers/dst_lpa_results_controller.rb
- cdx_core/app/controllers/microscopy_results_controller.rb
- cdx_core/app/controllers/patient_results_controller.rb
- cdx_core/app/controllers/xpert_results_controller.rb
- cdx_core/app/middleware/patient_results/persistence.rb
- cdx_core/app/middleware/patient_results/presenter.rb
- cdx_core/app/views/culture_results/_form.haml
- cdx_core/app/views/dst_lpa_results/_form.haml
- cdx_core/app/views/microscopy_results/_form.haml
- cdx_core/app/views/xpert_results/_form.haml
- cdx_core/config/locales/select.en.yml
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/spec/controllers/culture_results_controller_spec.rb
- cdx_core/spec/controllers/patient_results_controller_spec.rb
- cdx_core/spec/middleware/patient_results/persistence_spec.rb
- cdx_core/spec/middleware/test_orders/presenter_spec.rb
https://find.plan.io/projects/cdx/issues
> Add comment

- cdx_core/app/assets/javascripts/components/test_batch/show_rejected_with_comment.js.jsx
- cdx_core/app/middleware/patient_results/presenter.rb
- cdx_core/config/locales/select.en.yml
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/spec/middleware/test_orders/presenter_spec.rb
https://find.plan.io/issues/2381
> Rename samples collected to pending.

- cdx_core/config/locales/views/js_screen_views.en.yml
> Updated word in langauge file

- cdx_core/config/locales/views/episodes.en.yml
> Switch the Edit and the New labels for the Episode Heading

- cdx_core/app/assets/javascripts/menu.js
- cdx_core/app/assets/stylesheets/_layout.scss
- cdx_core/app/assets/stylesheets/_newdash.scss
> Better Account menu code

- cdx_core/app/views/episodes/_form.haml
> fixed and updated js for episodes screen

- cdx_core/app/controllers/alert_groups_controller.rb
- cdx_core/app/controllers/application_controller.rb
- cdx_core/app/controllers/device_models_controller.rb
- cdx_core/app/controllers/devices_controller.rb
- cdx_core/app/controllers/patients_controller.rb
- cdx_core/app/controllers/sites_controller.rb
- cdx_core/app/models/computed_policy.rb
- cdx_core/spec/controllers/device_models_controller_spec.rb
- cdx_core/spec/controllers/patients_controller_spec.rb
- cdx_core/spec/models/policy_spec.rb
https://find.plan.io/issues/2416
> Replace method prepare_for_institution_and_authorize with authorize_resource.

- cdx_core/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- cdx_core/config/locales/views/js_screen_views.en.yml
- cdx_vietnam/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
https://find.plan.io/issues/2265
> Do not hide comments textarea.

- .gitignore
- cdx_core/app/assets/javascripts/components/encounter_show.js.jsx
- cdx_core/app/assets/javascripts/components/paginator.js.jsx
- cdx_core/app/assets/javascripts/components/patients/show/history/patient_audit_logs.js.jsx
- cdx_core/app/assets/javascripts/components/test_orders/print_sample_id_button.js.jsx
- cdx_core/app/assets/stylesheets/_newlayout.scss
- cdx_core/app/assets/stylesheets/barcode-print.scss
- cdx_core/app/assets/stylesheets/page-print.scss
- cdx_core/app/controllers/encounters_controller.rb
- cdx_core/app/helpers/application_helper.rb
- cdx_core/app/helpers/encounters_helper.rb
- cdx_core/app/middleware/patient_logs/presenter.rb
- cdx_core/app/models/encounter.rb
- cdx_core/app/views/encounters/show.html.haml
- cdx_core/app/views/layouts/application.html.haml
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/lib/cdx_core/engine.rb
- cdx_core/spec/controllers/encounters_controller_spec.rb
- cdx_core/spec/middleware/patient_logs/presenter_spec.rb
- cdx_vietnam/app/assets/javascripts/components/encounter_show.js.jsx
https://find.plan.io/issues/2452
> Print sample barcode

- cdx_core/app/middleware/test_orders/status.rb
- cdx_core/spec/middleware/test_orders/presenter_spec.rb
- cdx_core/spec/middleware/test_orders/status_spec.rb
https://find.plan.io/issues/2269
> Change status to in progress if any test is pending approval.

- cdx_core/app/models/patient_result.rb
- cdx_core/app/views/culture_results/show.haml
- cdx_core/app/views/dst_lpa_results/show.haml
- cdx_core/app/views/microscopy_results/show.haml
- cdx_core/app/views/xpert_results/show.haml
- cdx_core/config/locales/models/culture_result.en.yml
- cdx_core/config/locales/models/dst_lpa_result.en.yml
- cdx_core/config/locales/models/microscopy_result.en.yml
- cdx_core/config/locales/models/xpert_result.en.yml
- cdx_core/spec/models/patient_result_spec.rb
https://find.plan.io/issues/2270
> Add feedback message to show view.

- cdx_vietnam/app/assets/javascripts/components/encounters/requested_tests.js.jsx
https://find.plan.io/issues/2457
> Remove creation of culture tests in vietnam.

- cdx_vietnam/Gemfile
- cdx_vietnam/app/assets/javascripts/components/patients/social_security_code.js.jsx
- cdx_vietnam/app/controllers/patients_controller_decorator.rb
- cdx_vietnam/app/models/patient_decorator.rb
- cdx_vietnam/app/views/patients/_form.html.haml
- cdx_vietnam/config/locales/models/patient.en.yml
- cdx_vietnam/db/migrate/20161017140902_skip_ssc_validation.rb
- cdx_vietnam/spec/models/patient_spec.rb
- db/schema.rb
https://find.plan.io/issues/2259
> Avoid patient ssc validation if users selects so.

- cdx_core/app/controllers/application_controller.rb
- cdx_core/app/controllers/roles_controller.rb
- cdx_core/app/controllers/test_orders_state_controller.rb
- cdx_core/app/middleware/xpert_results/importer.rb
- cdx_core/config/routes.rb
- cdx_core/spec/controllers/roles_controller_spec.rb
- cdx_core/spec/controllers/test_orders_state_controller_spec.rb
- cdx_vietnam/app/middleware/xpert_results/vietnam_importer.rb
- cdx_vietnam/spec/middleware/importer/single_message_processor_spec.rb
- cdx_vietnam/spec/middleware/xpert_results/vietnam_importer_spec.rb
- Added export test status to csv for Mo
- Ensure a nil sample id will generate an orphan result
- Change CPDSAMPLE to CDPSAMPLE
- Ensure Institution Read role can not be deleted because  It's compulsory for new users.
> Fix some issues

- cdx_core/spec/dummy/db/schema.rb
Super small PR. However, rake test loads the schema wrong at the moment.
> update spec schema

- cdx_vietnam/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
https://find.plan.io/issues/2496
> Remove blood from sample selection in Vietnam.

- cdx_core/app/models/xpert_result.rb
- cdx_core/spec/models/xpert_result_spec.rb
https://find.plan.io/issues/2499
> Validate rif is not required in model.

- cdx_core/app/controllers/patient_test_results_controller.rb
https://find.plan.io/issues/2436
> Fix sort problems.

- cdx_core/app/assets/javascripts/components/encounter_new.js.jsx
- cdx_core/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
https://find.plan.io/issues/2494
> Default performing site same as requesting site.

- cdx_core/app/assets/javascripts/components/encounter_new.js.jsx
- cdx_core/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- cdx_vietnam/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
It doesn't like this was implemented correctly originally. It now actually updates the field in the database.
> #2053 Fix presumptive_rr implementation

- cdx_core/app/assets/javascripts/components/encounter_show.js.jsx
- cdx_core/app/middleware/test_orders/persistence.rb
- cdx_vietnam/app/assets/javascripts/components/encounter_show.js.jsx
Missed a file. Display Presumptive RR on `encounters#show`.
> presumptive rr not on encounters#show

- cdx_core/app/assets/stylesheets/barcode-print.scss
https://find.plan.io/issues/2549
> Remove top margin.

- cdx_core/app/assets/javascripts/components/test_orders/test_orders_list.js.jsx
- cdx_core/app/models/entity_csv_builder.rb
- cdx_core/config/locales/models/encounters.en.yml
- cdx_vietnam/app/assets/javascripts/components/test_orders/test_orders_list.js.jsx
https://find.plan.io/issues/2317
> Fix wrong order column name.

- Procfile.local
- cdx_core/app/middleware/persistence/users.rb
- cdx_core/spec/controllers/users_controller_spec.rb
- cdx_core/spec/middleware/persistence/users_spec.rb
- cdx_core/spec/spec_helper.rb
- Also modified Procfile.local so I could start sidekiq jobs with my
local rails stack `bundle exec foreman start -f Procfile.local`
> Send email asycronously

- cdx_core/app/assets/javascripts/components/patients/show/history/patient_history.js.jsx
- cdx_core/app/assets/javascripts/components/patients/show/history/patient_history_content.js.jsx
#2532 Moved 'History' tab on `patients#show` to third.
> move history tab on patients view

- cdx_core/app/middleware/sample_identifiers/finder.rb
- cdx_core/app/middleware/samples/persistence.rb
- cdx_core/app/middleware/test_results/importer.rb
- cdx_core/app/middleware/xpert_results/finder.rb
- cdx_core/app/middleware/xpert_results/importer.rb
- cdx_core/app/models/sample_identifier.rb
- cdx_core/app/models/xpert_result.rb
- cdx_core/spec/middleware/xpert_results/importer_spec.rb
- cdx_core/spec/models/xpert_result_spec.rb
- cdx_vietnam/app/middleware/xpert_results/vietnam_importer.rb
- cdx_vietnam/spec/middleware/test_orders/presenter_spec.rb
- cdx_vietnam/spec/middleware/xpert_results/vietnam_importer_spec.rb
https://find.plan.io/issues/2528
> Allow link sample

- cdx_vietnam/app/assets/javascripts/components/patients/medical_insurance_num.js.jsx
- cdx_vietnam/app/views/patients/_form.html.haml
- cdx_vietnam/config/locales/views/cdx_vietnam/patients.en.yml
Warn users when the MI number is not valid.
> warn on mi format

- cdx_core/app/assets/javascripts/components/encounters/new/presumptive_rr.js.jsx
- cdx_core/app/controllers/application_controller.rb
- cdx_core/app/controllers/concerns/context.rb
- cdx_core/app/controllers/registrations_controller.rb
- cdx_core/app/controllers/test_orders_state_controller.rb
- cdx_core/app/controllers/test_results_controller.rb
- cdx_core/app/middleware/culture_results/presenter.rb
- cdx_core/app/middleware/dst_lpa_results/presenter.rb
- cdx_core/app/middleware/finder/microscopy_results.rb
- cdx_core/app/middleware/finder/test_results.rb
- cdx_core/app/middleware/microscopy_results/presenter.rb
- cdx_core/app/middleware/test_results/csv_generator.rb
- cdx_core/app/middleware/xpert_results/presenter.rb
- cdx_core/app/views/test_results/_culture_results.haml
- cdx_core/app/views/test_results/_device_results.haml
- cdx_core/app/views/test_results/_dst_lpa_results.haml
- cdx_core/app/views/test_results/_microscopy_results.haml
- cdx_core/app/views/test_results/_xpert_results.haml
- cdx_core/spec/controllers/test_results_controller_spec.rb
- cdx_core/spec/middleware/culture_results/presenter_spec.rb
- cdx_core/spec/middleware/dst_lpa_results/presenter_spec.rb
- cdx_core/spec/middleware/microscopy_results/presenter_spec.rb
- cdx_core/spec/middleware/xpert_results/presenter_spec.rb
https://find.plan.io/issues/2474
> Csv export in all test results tabs

- cdx_vietnam/lib/cdx_vietnam/presenters/vtm.rb
Fix the critical issue that prevents patient from being synced to VTM
> Fix VTM sync error

- cdx_core/app/assets/javascripts/cdx_core.js
- cdx_core/app/assets/stylesheets/_layout.scss
- cdx_core/app/views/encounters/show.html.haml
Clear up test order finance buttons with approval of alerts
> 2483 - Show alert for none Chrome browsers

- cdx_core/app/controllers/encounters_controller.rb
- cdx_core/app/models/concerns/patient_concern.rb
- cdx_core/app/views/patients/show.html.haml
- cdx_core/spec/controllers/encounters_controller_spec.rb
- cdx_core/spec/models/patient_spec.rb
https://find.plan.io/issues/2564
> Do not create test orders if patient has no active episode.

- cdx_core/app/models/xpert_result.rb
- cdx_core/spec/models/xpert_result_spec.rb
https://find.plan.io/issues/2568
> Add new results to allowed tuberculosis results.

- cdx_vietnam/app/middleware/middleware/integration/client.rb
This is the fix for the process looping caused by the Vietnam API Client.
It was a silly mistake, sorry for the inconvenience
> fix infinity loop

- cdx_core/app/models/encounter.rb
- cdx_core/config/locales/models/encounters.en.yml
- cdx_core/config/locales/select.en.yml
- cdx_core/spec/models/encounter_spec.rb
- cdx_vietnam/config/locales/models/encounters.vi.yml
- cdx_vietnam/config/locales/select.vi.yml
https://find.plan.io/issues/2577
> Remove pending approval status from test orders.

- cdx_core/app/middleware/test_orders/finder.rb
- cdx_core/app/models/encounter.rb
- cdx_core/config/locales/select.en.yml
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/spec/controllers/test_orders_state_controller_spec.rb
https://find.plan.io/issues/2578
> Remove not financed from outstanding test orders.

- cdx_vietnam/app/assets/javascripts/components/patients/show/history/patient_test_order.js.jsx
https://find.plan.io/issues/2533
> Update names to right ones.

- cdx_core/app/assets/javascripts/components/encounter_show.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_row.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_result_status.js.jsx
- cdx_core/config/locales/views/js_screen_views.en.yml
- cdx_vietnam/app/assets/javascripts/components/encounter_show.js.jsx
https://find.plan.io/issues/2420
> Display comments on test order.

- cdx_core/app/controllers/culture_results_controller.rb
- cdx_core/app/controllers/dst_lpa_results_controller.rb
- cdx_core/app/controllers/microscopy_results_controller.rb
- cdx_core/app/controllers/xpert_results_controller.rb
- cdx_core/app/middleware/samples/persistence.rb
- cdx_core/app/middleware/xpert_results/persistence.rb
- cdx_core/spec/controllers/encounters_controller_spec.rb
- cdx_core/spec/models/patient_spec.rb
https://find.plan.io/issues/2502
> Ensure times are saved properly.

- cdx_core/app/helpers/barcode_helper.rb
https://find.plan.io/issues/2581
> Reduce height of barcode to 1/3.

- cdx_vietnam/app/middleware/middleware/integration/client.rb
Fix the issue with RETRY (an integration request)
> fix error may be occur when sync between cdp and other system

- cdx_core/app/models/encounter.rb
- cdx_core/config/locales/models/encounter.en.yml
- cdx_core/spec/controllers/encounters_controller_spec.rb
https://find.plan.io/issues/2626
> Ensure test results are deleted when encounter is deleted.

- cdx_vietnam/app/models/patient_result_decorator.rb
fix duplicate patient when sync to etb
> fix duplicate patient when sync to etb

- cdx_core/app/assets/javascripts/components/encounters/new/presumptive_rr.js.jsx
- cdx_core/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
- cdx_vietnam/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
https://find.plan.io/issues/2615
> Update checkbox status when clicked.

- cdx_core/app/assets/javascripts/cdx_core.js
- cdx_core/app/controllers/xpert_results_controller.rb
- cdx_core/app/models/patient_result.rb
- cdx_core/app/views/xpert_results/_form.haml
https://find.plan.io/issues/2502
> Use datetime picker not just a date picker.

- cdx_core/app/assets/javascripts/components/test_orders/test_orders_list.js.jsx
- cdx_core/app/middleware/test_orders/finder.rb
- cdx_core/config/locales/views/js_components.en.yml
- cdx_core/lib/patient_results/finder_filters.rb
- cdx_core/lib/reports/all_tests.rb
- cdx_core/spec/lib/reports/all_tests_spec.rb
- cdx_core/spec/lib/reports/failed_spec.rb
- cdx_core/spec/middleware/patient_results/finder_spec.rb
- cdx_core/spec/middleware/test_orders/finder_spec.rb
- cdx_core/spec/middleware/test_results/finder_spec.rb
- https://find.plan.io/issues/2578
- Reorder dashboard chart (requested by Jack T.)
- Change test results start date (requested by Mo)
> Status not financed

- cdx_vietnam/app/models/patient_result_decorator.rb
- cdx_vietnam/lib/cdx_vietnam/presenters/etb.rb
This is to fix the two issues
https://find.plan.io/issues/2643
https://find.plan.io/issues/2644
> fix siteofdisease and mdrcasetype

- cdx_core/app/middleware/patients/finder.rb
- cdx_core/app/models/concerns/patient_concern.rb
https://find.plan.io/issues/2653
> Fix wrong search in patients.

- cdx_core/app/controllers/test_orders_state_controller.rb
- cdx_core/app/middleware/test_orders/audit_csv.rb
- cdx_core/config/locales/views/test_orders.en.yml
- cdx_core/spec/controllers/test_orders_state_controller_spec.rb
- cdx_core/spec/middleware/test_orders/audit_csv_spec.rb
https://find.plan.io/issues/2654
> update test order csv

- cdx_vietnam/app/middleware/xpert_results/vietnam_importer.rb
- cdx_vietnam/spec/middleware/importer/single_message_processor_spec.rb
Match CDPSAMPLE in caps, or lowercase.
> case insensitive matching in notes field

- db/seeds/manifests/genexpert_manifest.json
Update the genexpert seed manifest file to keep in line with the current manifest in production.
> update example genexpert manifest for end_time fix && init version

- cdx_core/app/middleware/samples/persistence.rb
- cdx_core/config/locales/views/samples.en.yml
- cdx_core/spec/middleware/samples/persistence_spec.rb
https://find.plan.io/issues/2669
> Return error message if empty sample ids.

- cdx_core/app/views/device_messages/index.haml
https://find.plan.io/issues/2610
> Add back missing text.

- Gemfile
- Gemfile.lock
- cdx_core/Gemfile
- cdx_core/Gemfile.lock
- cdx_core/app/models/site.rb
- cdx_core/lib/patient_results/finder_filters.rb
https://find.plan.io/issues/2595
> Ensure that all subsite info is displayed.

- cdx_core/app/middleware/finder/manual_results.rb
- cdx_core/app/middleware/patient_results/persistence.rb
- cdx_core/app/middleware/test_orders/finder.rb
- cdx_core/spec/middleware/patient_results/persistence_spec.rb
https://find.plan.io/issues/2674
https://find.plan.io/issues/2675
https://find.plan.io/issues/2676
> Include all subsites in filter.

- cdx_core/spec/middleware/samples/persistence_spec.rb
https://find.plan.io/issues/2669
> Improve test.

- cdx_core/db/migrate/20161122173610_add_indexes.rb
- cdx_vietnam/db/migrate/20161123095637_add_indexes_to_vietnam.rb
- db/schema.rb
https://find.plan.io/issues/2678
> Add missing indexes

- cdx_core/app/middleware/microscopy_results/presenter.rb
- cdx_core/spec/middleware/microscopy_results/presenter_spec.rb
- cdx_core/spec/models/microscopy_result_spec.rb
https://find.plan.io/issues/2662
> Improve microscopy result csv.

- cdx_core/app/middleware/test_orders/list_csv.rb
- cdx_core/config/locales/models/encounter.en.yml
- cdx_core/spec/controllers/test_orders_state_controller_spec.rb
- cdx_core/spec/middleware/test_orders/list_csv_spec.rb
https://find.plan.io/issues/2660
> Improve test order csv

- Gemfile
- Gemfile.lock
- cdx_core/Gemfile
- cdx_core/Gemfile.lock
- cdx_core/spec/support/blueprints.rb
- db/schema.rb
- lib/tasks/test_data.rake
A rake task to generate dummy data to the app.
> Add rake tast to generate dummy data.

- Gemfile
- Gemfile.lock
- cdx_core/app/controllers/test_results_controller.rb
- cdx_core/app/middleware/sample_identifiers/presenter.rb
- cdx_core/app/middleware/test_results/finder.rb
- cdx_core/app/middleware/test_results/presenter.rb
- cdx_core/app/models/test_result.rb
- cdx_core/config/locales/select.en.yml
- cdx_core/lib/reports/all_tests.rb
- cdx_core/lib/reports/daily_order_status.rb
- cdx_core/spec/support/blueprints.rb
- config/environments/development.rb
- lib/tasks/test_data.rake
https://find.plan.io/issues/2684
> Orphan tests csv stall on vn1

- cdx_core/config/locales/select.en.yml
- cdx_vietnam/app/middleware/test_orders/list_csv_decorator.rb
- cdx_vietnam/spec/middleware/test_orders/list_csv_spec.rb
https://find.plan.io/issues/2686
> Remove test order due date in Vietnam.

- cdx_core/app/middleware/test_orders/status.rb
- cdx_core/spec/middleware/test_orders/status_spec.rb
- cdx_vietnam/lib/cdx_vietnam/presenters/vtm.rb
https://find.plan.io/issues/2704
> Do not duplicate status logs if new status is same as old.

- Gemfile
- cdx_core/Gemfile
- cdx_core/app/controllers/sites_controller.rb
- cdx_core/app/models/encounter.rb
- cdx_core/app/views/sites/_form.html.haml
- cdx_core/config/locales/views/sites.en.yml
- cdx_core/db/migrate/20161130093341_financed_setting_by_site.rb
- cdx_core/spec/controllers/sites_controller_spec.rb
- cdx_core/spec/models/encounter_spec.rb
- db/schema.rb
https://find.plan.io/issues/2728
> Auto finance approval

- cdx_api_core/app/controllers/cdx_api_core/sites_controller.rb
- cdx_vietnam/app/assets/javascripts/components/patients/medical_insurance_num.js.jsx
- Fix medical insurance num js
- Added `.includes(:parent, :institution)` in the `/api/sites` call
> fix to medical insurance number js & add some includes to appease bullet

- cdx_core/app/controllers/devices_controller.rb
https://find.plan.io/issues/2665
> Add hostname to devices csv.

- cdx_core/app/models/custom_translation.rb
- cdx_core/db/migrate/20161206160546_add_new_finance_approval_content.rb
- cdx_vietnam/db/migrate/20161206160615_add_new_finance_approval_content_for_vietnam.rb
- db/schema.rb
https://find.plan.io/issues/2755
> Add new feedback message to finance approved.

- cdx_core/app/middleware/test_orders/finder.rb
- cdx_core/app/middleware/test_results/finder.rb
- cdx_core/app/views/test_orders/index.haml
- cdx_core/config/locales/views/test_orders.en.yml
https://find.plan.io/issues/2754
> Add search by patient name on test orders.

- cdx_vietnam/app/middleware/middleware/integration/etb_scraper.rb
Scraper for eTB Manager can no longer work correctly due to recent update to the eTB Manager system's UI. This is a hot fix to adapt the change in CDP scraper
> Fix ETB scraper (issue 2775)

- cdx_core/app/assets/javascripts/cdx_core.js
- cdx_core/app/assets/javascripts/components/encounters/new/footer.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_actions.js.jsx
- cdx_core/app/assets/javascripts/components/test_batch/test_batch_list.js.jsx
- cdx_vietnam/app/assets/javascripts/components/fresh_tests_encounter_form.js.jsx
https://find.plan.io/issues/2770
> Disable button when clicked.
